import { PRODUCTS as products } from './products-data.js';
const grid=document.querySelector('.catalog-grid');const results=document.querySelector('.catalog-results');const filters=[...document.querySelectorAll('[data-filter]')];const search=document.querySelector('.catalog-search input');const dialog=document.querySelector('.catalog-dialog');const dialogContent=dialog?.querySelector('.catalog-dialog__content');const modelHint=dialog?.querySelector('.catalog-dialog__model-hint');const videoPanel=dialog?.querySelector('.catalog-dialog__video');const productVideo=videoPanel?.querySelector('video');const nextButton=dialog?.querySelector('.catalog-dialog__next');let activeFilter='todos';let activeProductId=null;let lastTriggeredCard=null;
const productImage=(product)=>`../assets/catalogo/${encodeURIComponent(product.image)}`;
const productModel=(product)=>`../assets/catalogo/${encodeURIComponent(product.model)}`;
const productVideoUrl=(product)=>`../assets/catalogo/${encodeURIComponent(product.video)}`;
const visibleProducts=()=>{const query=search.value.trim().toLocaleLowerCase('es');return products.filter((product)=>{const categoryMatches=activeFilter==='todos'||product.category===activeFilter;const text=`${product.title} ${product.id} ${product.category}`.toLocaleLowerCase('es');return categoryMatches&&text.includes(query)})};
const render=()=>{const query=search.value.trim().toLocaleLowerCase('es');const visible=products.filter((product)=>{const categoryMatches=activeFilter==='todos'||product.category===activeFilter;const text=`${product.title} ${product.id} ${product.category}`.toLocaleLowerCase('es');return categoryMatches&&text.includes(query)});results.textContent=`${visible.length} ${visible.length===1?'referencia encontrada':'referencias encontradas'}`;grid.innerHTML=visible.length?visible.map((product)=>`<button class="catalog-card" type="button" data-product="${product.id}"><span class="catalog-card__image"><img src="${productImage(product)}" alt="${product.title}" loading="lazy" /></span><span class="catalog-card__body"><span><span class="catalog-card__category">${product.category}</span><h3>${product.title}</h3></span><span class="catalog-card__arrow" aria-hidden="true">↗</span></span></button>`).join(''):'<p class="catalog-empty">No hay referencias que coincidan con la búsqueda.</p>'};
const openProduct=(id)=>{const product=products.find((item)=>item.id===id);if(!product||!dialog||!dialogContent)return;activeProductId=product.id;const visible=visibleProducts();if(nextButton){nextButton.disabled=visible.findIndex((item)=>item.id===product.id)>=visible.length-1;}const hasModel=Boolean(product.model);const hasVideo=Boolean(product.video);const copy=`<div class="catalog-dialog__copy"><p class="catalog-eyebrow">${product.category}</p><div class="catalog-dialog__title-row"><h2 id="dialog-title">${product.title}</h2></div><p>${product.description}</p><a href="../#contacto">Solicitar información →</a></div>`;const photo=(!hasModel&&!hasVideo)?`<div class="catalog-dialog__photo"><img src="${productImage(product)}" alt="${product.title}" /></div>`:'';const model=hasModel?`<div class="catalog-dialog__model"><model-viewer src="${productModel(product)}" alt="Modelo 3D de ${product.title}" camera-controls auto-rotate shadow-intensity="1"></model-viewer></div>`:'';dialog.classList.toggle('has-video',hasVideo);dialog.classList.toggle('has-model',hasModel);dialogContent.classList.toggle('is-quad',hasVideo);dialogContent.innerHTML=`${copy}${model}${photo}`;if(modelHint){modelHint.hidden=!hasModel;if(hasModel){const modelBox=dialogContent.querySelector('.catalog-dialog__model');modelBox?.append(modelHint);}}if(videoPanel&&productVideo){videoPanel.hidden=!hasVideo;dialogContent.append(videoPanel);if(hasVideo){productVideo.src=productVideoUrl(product);productVideo.play().catch(()=>{});}else{productVideo.pause();productVideo.removeAttribute('src');productVideo.load();}}if(!dialog.open)dialog.showModal()};
const openNextProduct=()=>{const visible=visibleProducts();const currentIndex=visible.findIndex((product)=>product.id===activeProductId);const nextProduct=visible[currentIndex+1];if(nextProduct)openProduct(nextProduct.id)};
filters.forEach((button)=>button.addEventListener('click',()=>{activeFilter=button.dataset.filter;filters.forEach((item)=>item.classList.toggle('is-active',item===button));render()}));
search?.addEventListener('input',render);grid?.addEventListener('click',(event)=>{const card=event.target.closest('[data-product]');if(card){lastTriggeredCard=card;card.focus();openProduct(card.dataset.product)}});nextButton?.addEventListener('click',openNextProduct);dialog?.addEventListener('close',()=>{const card=lastTriggeredCard;lastTriggeredCard=null;if(card&&card.isConnected){requestAnimationFrame(()=>card.focus())}});dialog?.querySelector('.catalog-dialog__close')?.addEventListener('click',()=>dialog.close());dialog?.addEventListener('click',(event)=>{if(event.target===dialog)dialog.close()});
const menuButton=document.querySelector('.catalog-menu');const nav=document.querySelector('.catalog-nav');menuButton?.addEventListener('click',()=>{const isOpen=nav.classList.toggle('is-open');menuButton.setAttribute('aria-expanded',String(isOpen))});nav?.querySelectorAll('a').forEach((link)=>link.addEventListener('click',()=>{nav.classList.remove('is-open');menuButton?.setAttribute('aria-expanded','false')}));
render();
const initialHash = window.location.hash.replace('#', '');
if (initialHash) {
	openProduct(initialHash);
}
document.querySelector('.back-to-top')?.addEventListener('click',(event)=>{event.preventDefault();window.scrollTo({top:0,behavior:'smooth'});history.replaceState(null,'','#inicio')});